### ISSUE TITLE
Discord commands have no effect at all

### ISSUE THREAD

**Issue by iwishiknewcoding** [gabrielbrop/haxball-server#10]
Hello @gabrielbrop, thanks for the awesome package. Though it does not quite work for me. Would appreciate some help here.

The thing is, in the server when I do `haxball-server open` this is the output:
```bash
[11:11:47] [REMOTE DEBUGGING] Listening to remote connections on port 9500
[11:11:48] [DISCORD] Logged in as mybot#0001!
```
and I expect Discord commands to work as expected, but when I type them in the channel where the bot is invited and has Administrator scopes, nothing is happening either in Discord or in server.

It's an Ubuntu server, and this is my config file:
```bash
$ cat config.json
{
    "server": {
        "execPath": "/snap/bin/chromium-browser",
        "userDataDir": "./path/to/data-dir"
    },
    "panel": {
        "bots": [
            {
                "name": "myroom",
                "displayName": "My room",
                "path": "./path/to/script.js"
            }
        ],
        "discordToken": "MTExsaMADSJXOASD.G-sad.JASXDlxsda", # placeholder
        "discordPrefix": "!",
        "mastersDiscordId": [
            "57994213123124" # placeholder
        ]
    }
}
```

Where should I start troubleshooting from? Or maybe I'm missing something?

**Comment by iwishiknewcoding** [comment]
oops, I just realized 😅

**Comment by Luis8a3010** [comment]
Could you teach me how to use this, I have followed the steps, but I feel like I am missing something, I don't know if it is yet, I need it for my Haxball vps please, could we contact you via discord
