### ISSUE TITLE
Usage and Communication

### ISSUE THREAD

**Issue by EmirhanOlgn** [gabrielbrop/haxball-server#2]
Hello, I didn't quite understand how to run this server, how to open more than one server. I have no idea how to design my own bot and I don't know its features. Can you explain them to me? And if appropriate, can I ask for your social media accounts you use such as Discord, Instagram? I want to contact @gabrielbrop

**Comment by EmirhanOlgn** [comment]
@gabrielbrop 
Hello again. I think I more or less understood the use of the bot, but I still don't know how to create the bot.
```js
"bot": [
             { "name": "example1", "displayName": "Example room 1", "path": "path/to/example1.js" },
             { "name": "example2", "displayName": "Example room 2", "path": "path/to/example2.js" }
         ],
```
I don't know what to write inside the javascript folder shown. Can you open a sample usage project and show some features?
for example: `room.sendAnnouncement`

**Comment by gabrielbrop** [comment]
About the error: [You need to install Chrome and specify its path in the configuration file](https://github.com/gabrielbrop/haxball-server#execpath-string).

This project won't help you create your room. This is nothing more than a simple interface over Puppeteer. People who have already developed their rooms need a way to make them run on a VPS/Cloud, and that's the problem this project solves.

You should check the Haxball Headless API and ask questions about Haxball development in [haxball-issues](https://github.com/haxball/haxball-issues/issues).
