### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by EmirhanOlgn** [gabrielbrop/haxball-server#3]
@gabrielbrop
Hello again. I think I more or less understood the use of the bot, but I still don't know how to create the bot.
```js
"bots": [
    { "name": "example1", "displayName": "Example room 1", "path": "path/to/example1.js" },
    { "name": "example2", "displayName": "Example room 2", "path": "path/to/example2.js" }
],
```
I don't know what to write inside the javascript folder shown. Can you open a sample usage project and show some features?
for example: room.sendAnnouncement

And I am getting an error like this:
```yml
Unable to open the room!
Error: Failed to launch the browser process! spawn your/path/to/chrome.exe ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
```
https://github.com/gabrielbrop/haxball-server/issues/2

**Comment by rocosttaa** [comment]
**I am not the creator of this, but you can only do this if you want:**

`"panel": {
        "bots": [
            {
                "name": "futsal",
                "path": "./bots/futsal.js"
            }
        ],`

**Comment by EmirhanOlgn** [comment]
Hello, thanks for the help. Another thing I can't do is I don't know how to make the file with the bot. Can you help me?
```yml
example1.js
```

**Comment by rocosttaa** [comment]
Mine, for example, is answering:

![image](https://user-images.githubusercontent.com/86488916/143464378-d1292985-0e12-49f1-9526-0f3dee03acd9.png)

**Comment by EmirhanOlgn** [comment]
This is not what I'm talking about. I don't know how to write the codes inside the file. require, room. and room settings.
