### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by hbenormous** [gabrielbrop/haxball-server#4]
![Captura de tela de 2021-11-26 01-43-58](https://user-images.githubusercontent.com/17686408/143528123-65f5026e-fb90-4be3-b8c5-818baa064b57.png)

Deu esse erro.
Tentei como usuário root e tbm deu o mesmo erro.
Teria como me ajudar a resolver?

**Comment by gabrielbrop** [comment]
Isto não é um erro, mas somente um aviso de deprecação. A instalação ocorreu normalmente.

Haxball Server foi feito com discord.js 12 mas eles lançaram a versão 13 recentemente.

Futuramente irei atualizar para a versão 13 (ou mudar para uma API cujas versões durem mais), mas, no momento, usar a versão 12 não tem nenhum problema.

**Comment by hbenormous** [comment]
> Isto não é um erro, mas somente um aviso de deprecação. A instalação ocorreu normalmente.
> 
> Haxball Server foi feito com discord.js 12 mas eles lançaram a versão 13 recentemente.
> 
> Futuramente irei atualizar para a versão 13 (ou mudar para uma API cujas versões durem mais), mas, no momento, usar a versão 12 não tem nenhum problema.

arrumei aqui.
desinstalei o pacote e instalei de novo e resolveu

**Comment by hbenormous** [comment]
> > Isto não é um erro, mas somente um aviso de deprecação. A instalação ocorreu normalmente.
> > Haxball Server foi feito com discord.js 12 mas eles lançaram a versão 13 recentemente.
> > Futuramente irei atualizar para a versão 13 (ou mudar para uma API cujas versões durem mais), mas, no momento, usar a versão 12 não tem nenhum problema.
> 
> arrumei aqui. desinstalei o pacote e instalei de novo e resolveu

apaguei o cache do discord.js globalmente
